### PR TITLE
Improvements to generated docs

### PR DESCRIPTION
**Pull request by 00xc**
* Fix markdown for `Errors` and `Panics` sections.
* Properly format field names.

### CODE REVIEW

**Comment by Robbepop** [comment]
Thank you for the improvements!

**Comment by 00xc** [comment]
Hi, could you review the changes? I believe the test failures are unrelated.

**Comment by 00xc** [comment]
Ping, could you merge this?

**Review by Robbepop — APPROVED** [review]
@00xc hey, I am very sorry. I didn't mean to ignore this PR. Thanks a lot for the improvements! LGTM. :)

**Pull request merged**
